name: Run Modbus Automation

on:
  schedule:
    - cron: "0 * * * *"  # every hour on the hour
  workflow_dispatch:      # allows you to run it manually from the Actions tab

jobs:
  run-modbus:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run orchestrator (server → client → stop)
        run: |
          python run_modbus.py

      - name: Upload logs
        if: always()
        run: |
          mkdir -p logs
          echo "Workflow completed at $(date)" > logs/run_summary.txt
        # Save logs as downloadable artifact
      - name: Upload log artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: modbus-run-logs
          path: logs/
