name: Run Modbus Automation (Baseline Test)

on:
  workflow_dispatch:      # Manual trigger only for now

jobs:
  test-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Run log creation test
        run: python run_modbus.py

      - name: Debug list directory
        run: |
          echo "=== Listing repo root ==="
          pwd
          ls -R
          echo "========================"

      - name: Upload log artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: modbus-logs
          path: logs/
