name: Run Modbus Automation

on:
  workflow_dispatch:      # Manual run
  schedule:
    - cron: "0 * * * *"   # Hourly

jobs:
  run-modbus:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install pymodbus==3.6.8

      - name: Run Modbus Orchestrator
        run: python run_modbus.py

      - name: Debug log folder
        run: |
          echo "Listing generated log directories:"
          ls -R logs || echo "⚠️ No logs found"

      - name: Upload Modbus log artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: modbus-logs
          path: logs/
