name: Run Modbus Automation

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"   # every hour

jobs:
  run-modbus:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Modbus orchestrator
        run: python run_modbus.py

      - name: Show logs
        run: |
          echo "Listing logs directory:"
          ls -R logs || echo "⚠️ No logs created!"

      - name: Upload Modbus log artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: modbus-logs
          path: logs/
