name: Run Modbus Automation (Robot Framework)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"   # Every hour

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  run-modbus-robot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Generate timestamped folder name
        id: time
        run: echo "FOLDER_NAME=$(date +'%Y-%m-%d-%Hh')" >> $GITHUB_ENV

      - name: Run Robot Framework tests
        run: |
          mkdir -p logs/${{ env.FOLDER_NAME }}
          robot -d logs/${{ env.FOLDER_NAME }} tests/modbus_automation.robot

      - name: Upload Robot logs (Artifacts)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: robot-reports-${{ env.FOLDER_NAME }}
          path: logs/${{ env.FOLDER_NAME }}/

      - name: Deploy HTML Reports to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: logs
          publish_branch: gh-pages
          commit_message: "Auto publish Robot Framework HTML reports for ${{ env.FOLDER_NAME }}"





#/*
#name: Run Modbus Automation
#
#on:
#  workflow_dispatch:
#  schedule:
#    - cron: "0 * * * *"   # every hour
#
#jobs:
#  run-modbus:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v4
#
#      - name: Set up Python
#        uses: actions/setup-python@v5
#        with:
#          python-version: "3.10"
#
#      - name: Install dependencies
#        run: pip install -r requirements.txt
#
#      - name: Run Modbus orchestrator
#        run: python run_modbus.py
#
#      - name: Show logs
#        run: |
#          echo "Listing logs directory:"
#          ls -R logs || echo "⚠️ No logs created!"
#
#      - name: Upload Modbus log artifacts
#        if: always()
#        uses: actions/upload-artifact@v4
#        with:
#          name: modbus-logs
#          path: logs/
#*/