name: Run Modbus Automation

on:
  schedule:
    - cron: "0 * * * *"  # every hour
  workflow_dispatch:

jobs:
  run-modbus:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Modbus orchestrator (server → client → stop)
        run: python run_modbus.py

      - name: Verify logs exist
        run: |
          echo "Checking logs directory..."
          ls -R logs || echo "⚠️ No logs directory found!"

      - name: Upload Modbus log artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: modbus-logs
          path: logs/
